name: PlatformIO

on:
  pull_request:
    branches:
      - devel
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          pio pkg update 
      - name: Install ICENAV Custom Board json
        run: |
             cp **/tools/esp32-s3-devkitc-1-n16r8v.json ~/.platformio/platforms/espressif32/boards
      - name: Testing ICENAV Custom Board
        run: |
          export ICENAV3_LON=13.404
          export ICENAV3_LAT=52.520
          pio run
      - name: Testing ESP32S3 MakerFabs Board
        run: |
          export ICENAV3_LON=13.404
          export ICENAV3_LAT=52.520
          pio run -e MAKERF_ESP32S3
 
