name: Schedule

on:
  schedule:
    - cron:  '30 10 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          pio pkg update
      - name: Testing all
        run: |
          export ICENAV3_LON=13.404
          export ICENAV3_LAT=52.520
          pio run -e CUSTOMBOARD -e MAKERF_ESP32S3
 
 

